
# ingress-controller 설치 명령어
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/aws/deploy.yaml


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-backend-ingress
  namespace: woonglab
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: my-issuer
spec:
  tls:
  - hosts:
    - "server.woonglab.site"
    # https설정시에 TLS 인증서가 저장된 certificate의 Secret의 이름(spec.secretName)을 지정
    secretName: server-woonglab-com-tls
  rules:
  - host: server.woonglab.site 
    http:
      paths:
      - path: / #모든 url요청을 service로 라우팅
        pathType: Prefix
        backend:
          service:
            name: ordersystem-backend-service
            #depl-svc의 서비스 name과 일치 (metadata)
            port:
              number: 80
