apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitor-woonglab-com-tls
  namespace: monitoring
spec:
  secretName: monitor-woonglab-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: monitor.woonglab.site
  dnsNames:
  - monitor.woonglab.site