name: deploy order order-backend

on:
  push:
    branches:
      - main
    # 기본 브랜치는 main이며 main의 소스코드 변경사항이 발생하면 아래 job들을 실행하겠다.

    # 1. 소스코드 클론 2. kubectl 설치 3. aws cli 설치 및 configure (변수처리 불러옴 -> 깃허브 세팅에 넣어서 보관)  
    # 4. kubectl 설치 및 cluster 설정 4. ECR 로그인 명령어 5. 빌드 & 푸시 6. 롤아웃 리스타트 -> 이미지 빌드 파드 재생성

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
        
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name  my-cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY: 131745734106.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: order-backend
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./2.ordersystem/Dockerfile ./2.ordersystem
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        # 루트 위치에서 접근하기 때문에 -F옵션 경로 지정해야함  

      - name: eks kubectl apply
        run: |
          kubectl rollout restart deployment ordersystem-backend -n woonglab
        # kubectl apply -f ./2.ordersystem/k8s/k8s-ordersystem/depl_svc.yml